//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopWallpaperAutoSwitch.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopWallpaperAutoSwitch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;multilang language=&quot;English(en-US)&quot;&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Wallpaper Auto Switch&lt;/key&gt;
        ///    &lt;value&gt;Desktop Wallpaper Auto Switch&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Orientation:&lt;/key&gt;
        ///    &lt;value&gt;Desktop Orientation:&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Landscape&lt;/key&gt;
        ///    &lt;value&gt;Landscape&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Portrait&lt;/key&gt;
        ///    &lt;value&gt;Portrait&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Landscape image:&lt;/key&gt;
        ///    &lt;value&gt;L [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string dwas_en_US {
            get {
                return ResourceManager.GetString("dwas_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;multilang language=&quot;中文(zh-CN)&quot;&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Wallpaper Auto Switch&lt;/key&gt;
        ///    &lt;value&gt;桌面背景自动切换&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Orientation:&lt;/key&gt;
        ///    &lt;value&gt;当前屏幕方向：&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Landscape&lt;/key&gt;
        ///    &lt;value&gt;水平&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Portrait&lt;/key&gt;
        ///    &lt;value&gt;垂直&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Landscape image:&lt;/key&gt;
        ///    &lt;value&gt;水平图片：&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Portra [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string dwas_zh_CN {
            get {
                return ResourceManager.GetString("dwas_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon landscape {
            get {
                object obj = ResourceManager.GetObject("landscape", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon portrait {
            get {
                object obj = ResourceManager.GetObject("portrait", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
